### ISSUE TITLE
Paid lightning invoice does not deposit to the cash account

### ISSUE THREAD

**Issue by sbddesign** [Marfusios/strike-btcpayserver-plugin#3]
Thanks for the great plugin! I noticed something interesting when using this. Having worked with the Strike API previously, I have been able to fetch lightning invoices that deposit directly into the cash account as USD. However, when using this plugin, it appears to deposit into the bitcoin account and then immediately sell this.

This seems like it complicates the accounting with "sale events" and also runs the risk of creating taxable events if the price varies between receipt and sale.

Is there a way this plugin could deposit directly to the cash account instead of looping through the bitcoin account first?

**Comment by Marfusios** [comment]
@sbddesign 
You are right. We had to use this "invoice+exchange" approach because Strike API was designed in a FIAT-centric way (with very short-lived quotes that give you a guaranteed FIAT price for 1-2 minutes). This doesn't play well with BtcPayServer because they do the calculations from/to FIAT on their own. 

But I have good news! I'm in the middle of integrating a brand-new API -  [receive requests](https://docs.strike.me/api/create-a-receive-request). 
It should give us exactly what we need, creating LN invoices that will be converted to FIAT upon receival, without triggering tax events.

**Comment by Marfusios** [comment]
The new version 1.3.2 was released. 
Let me know if everything works as expected on your side. 
Don't forget to regenerate API keys with the new scopes. 

![image](https://github.com/user-attachments/assets/1e0f48e6-9e97-460b-aa41-3410af912153)

**Comment by sbddesign** [comment]
@Marfusios Ah, sorry I missed this message earlier. Yes, I should have time to run the update this upcoming week and test it out. Looking forward to trying it. Thank you!

**Comment by sbddesign** [comment]
@Marfusios It works perfectly, thank you!
